name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') != true
#    runs-on: windows-2022
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: mkdir build ; echo ${{ github.sha }} > build/Release.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
