name: Build Demo 1

# There doesn't seem to be an easy way to trigger a build when a pull request is merged. 
# So we're just building any time a push is made to master. https://github.com/orgs/community/discussions/26724
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/') != true
#    runs-on: windows-2022
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: echo ${{ github.sha }} > build/Release.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
