name: Build Demo 1

on: [push, pull_request]

permissions:
  contents: write # needed to create releases

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: Release.txt
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build

  # release:
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build # just for example files...
  #       run: echo ${{ github.sha }} > Release.txt

  #     - name: Build Changelog
  #       id: github_release
  #       uses: mikepenz/release-changelog-builder-action@v4
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Create Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         body: ${{steps.github_release.outputs.changelog}}
  #         files: Release.txt
